name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Melakukan Deploy Ke Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd app-klinik && git pull origin master | composer dump-autoload | sudo php artisan migrate
    - name: Dump Autoload
      script: 'cd /home/nuris_akbar && ./server_deploy.sh'